# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2351619b0cee6a16aed51233d486b1ea4cd7a02c758932048d1ce24b72c649b48bb23cf07ae6eb9d52bfb208f9962d128f37b942a498c4cf3f3481bf2d2df997

test:
  secret_key_base: da3f907dfbe55422af4438553d6a596be318eb55bd8b2e05708bf66bfb72881b497049e3bd99a1eba5c4e1f28f91e20d2294f6c375ecbd900c69640490f11194

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
