# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)

Citie.create(name: 'a')
Citie.create(name: 'b')
Citie.create(name: 'c')
Citie.create(name: 'd')
Citie.create(name: 'e')
Citie.create(name: 'f')
Citie.create(name: 'g')
Citie.create(name: 'h')
Citie.create(name: 'i')
Citie.create(name: 'j')
Citie.create(name: 'k')
Citie.create(name: 'l')
Citie.create(name: 'm')
Citie.create(name: 'n')
Citie.create(name: 'o')
Citie.create(name: 'p')
Citie.create(name: 'q')
Citie.create(name: 'r')
Citie.create(name: 's')
Citie.create(name: 't')
Citie.create(name: 'u')
Citie.create(name: 'v')
Citie.create(name: 'w')
Citie.create(name: 'x')
Citie.create(name: 'y')
Citie.create(name: 'z')

Countrie.create(name: 'a')
Countrie.create(name: 'b')
Countrie.create(name: 'c')
Countrie.create(name: 'd')
Countrie.create(name: 'e')
Countrie.create(name: 'f')
Countrie.create(name: 'g')
Countrie.create(name: 'h')
Countrie.create(name: 'i')
Countrie.create(name: 'j')
Countrie.create(name: 'k')
Countrie.create(name: 'l')
Countrie.create(name: 'm')
Countrie.create(name: 'n')
Countrie.create(name: 'o')
Countrie.create(name: 'p')
Countrie.create(name: 'q')
Countrie.create(name: 'r')
Countrie.create(name: 's')
Countrie.create(name: 't')
Countrie.create(name: 'u')
Countrie.create(name: 'v')
Countrie.create(name: 'w')
Countrie.create(name: 'x')
Countrie.create(name: 'y')
Countrie.create(name: 'z')

River.create(name: 'a')
River.create(name: 'b')
River.create(name: 'c')
River.create(name: 'd')
River.create(name: 'e')
River.create(name: 'f')
River.create(name: 'g')
River.create(name: 'h')
River.create(name: 'i')
River.create(name: 'j')
River.create(name: 'k')
River.create(name: 'l')
River.create(name: 'm')
River.create(name: 'n')
River.create(name: 'o')
River.create(name: 'p')
River.create(name: 'q')
River.create(name: 'r')
River.create(name: 's')
River.create(name: 't')
River.create(name: 'u')
River.create(name: 'v')
River.create(name: 'w')
River.create(name: 'x')
River.create(name: 'y')
River.create(name: 'z')


